// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoyageManager.Infrastructure.Database;

#nullable disable

namespace VoyageManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713113527_AssignmentTableUpdated")]
    partial class AssignmentTableUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("voyage")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoyageManager.Domain.Models.CommandAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "State");

                    b.ToTable("CommandAssignments", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Groups", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.GroupAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("GroupId", "WorkerId")
                        .IsUnique();

                    b.ToTable("GroupAssignments", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCreateAssignments")
                        .HasColumnType("boolean");

                    b.Property<string>("EnrollmentSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchasedLicenses")
                        .HasColumnType("integer");

                    b.Property<int>("UsedLicenses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tenants", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Workers", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.CommandAssignment", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.Worker", "AssignedWorker")
                        .WithMany("CommandAssignments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedWorker");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Group", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.Tenant", "Tenant")
                        .WithMany("Groups")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.GroupAssignment", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.Group", "AssignedGroup")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoyageManager.Domain.Models.Worker", "AssignedWorker")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedGroup");

                    b.Navigation("AssignedWorker");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Worker", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.Tenant", "Tenant")
                        .WithMany("Workers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Group", b =>
                {
                    b.Navigation("GroupAssignments");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Tenant", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Worker", b =>
                {
                    b.Navigation("CommandAssignments");

                    b.Navigation("GroupAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
