// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoyageManager.Infrastructure.Database;

#nullable disable

namespace VoyageManager.Infrastructure.Migrations
{
    [DbContext(typeof(VoyageManagerDbContext))]
    [Migration("20260605120212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("voyage")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoyageManager.Domain.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EnrollmentSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchasedLicenses")
                        .HasColumnType("integer");

                    b.Property<int>("UsedLicenses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tenants", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("VoyagerAgents", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("VoyagerCommands", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerCommandAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("VoyagerAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoyagerCommandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoyagerCommandId");

                    b.HasIndex("VoyagerAgentId", "Status");

                    b.HasIndex("VoyagerAgentId", "VoyagerCommandId")
                        .IsUnique();

                    b.ToTable("VoyagerCommandAssignments", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("VoyagerGroups", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerGroupAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoyagerAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoyagerGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoyagerAgentId");

                    b.HasIndex("VoyagerGroupId", "VoyagerAgentId")
                        .IsUnique();

                    b.ToTable("VoyagerGroupAssignments", "voyage");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerAgent", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.Tenant", "Tenant")
                        .WithMany("VoyagerAgents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerCommandAssignment", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.VoyagerAgent", "VoyagerAgent")
                        .WithMany("CommandAssignments")
                        .HasForeignKey("VoyagerAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoyageManager.Domain.Models.VoyagerCommand", "VoyagerCommand")
                        .WithMany("CommandAssigments")
                        .HasForeignKey("VoyagerCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoyagerAgent");

                    b.Navigation("VoyagerCommand");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerGroup", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.Tenant", "Tenant")
                        .WithMany("VoyagerGroups")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerGroupAssignment", b =>
                {
                    b.HasOne("VoyageManager.Domain.Models.VoyagerAgent", "VoyagerAgent")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("VoyagerAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoyageManager.Domain.Models.VoyagerGroup", "VoyagerGroup")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("VoyagerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoyagerAgent");

                    b.Navigation("VoyagerGroup");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.Tenant", b =>
                {
                    b.Navigation("VoyagerAgents");

                    b.Navigation("VoyagerGroups");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerAgent", b =>
                {
                    b.Navigation("CommandAssignments");

                    b.Navigation("GroupAssignments");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerCommand", b =>
                {
                    b.Navigation("CommandAssigments");
                });

            modelBuilder.Entity("VoyageManager.Domain.Models.VoyagerGroup", b =>
                {
                    b.Navigation("GroupAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
